### ISSUE TITLE
use subprocess in analyze_suspend.py

### ISSUE THREAD

**Issue by TheRegRunner** [01org/suspendresume#3]
The script analyze_suspend.py uses os.popen() and os.system().

os.popen is deprecated.
os.popen and os.system can inject shell commands.

For example if a shell command is in the hostname it could get into self.prefix
https://bugs.launchpad.net/ubuntu/+source/bash/+bug/1507025

So please uses subprocess.
Thank you

**Comment by tebrandt** [comment]
I just finally got around to doing this, I replaced all os.system calls with subprocess.call and all os.popen calls with subprocess.Popen. Thanks for the catch!

https://github.com/01org/suspendresume/commit/0b1917d68f242cc95c5b3dc6463a2eb70ab7d256

**Comment by TheRegRunner** [comment]
Thanks, but still Shell is True, so still dangerous.
I would be happy if the commands and parameters are a list [ ] and not a single String.
